config/routes.rb
Rails.application.routes.draw do
  root 'companies#index'
  resources :companies
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.all
  end

  def show
  end

  def edit
  end

  def new
    @company = Company.new
  end

  def update
    @company.update(company_params)
    redirect_to @company
  end

  def create
    @company = Company.create(company_params)
    redirect_to @company
  end

  def destroy
    @company.destroy
    redirect_to root_path
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, :city, :nonprofit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.haml
=form_for @company, html: {role: "form"} do |f|

  =f.label :name
  =f.text_field :name

  =f.label :city
  =f.text_field :city

  =f.label :nonprofit
  =f.check_box :nonprofit

  =f.submit

app/views/companies/edit.html.haml
%h1 Edit Task
= render 'form'

app/views/companies/index.html.haml
%h1 Companies
=link_to "New Company", new_company_path
%table
  %thead
    %tr
      %th Name
      %th City
      %th Nonprofit?
      %th
  %tbody
    -@companies.each do |company|
      %tr
        %td=company.name
        %td=company.city
        %td=company.nonprofit
        %td
          .pull-right
            =link_to "Show", company
            =link_to "Edit", edit_company_path(company)
            =link_to "Delete", company, method: :delete, data: { confirm: 'Are you sure?' }

app/views/companies/new.html.haml
%h1 New Company
= render 'form'

app/views/companies/show.html.haml
%h1=@company.name
%p
  %strong City:
  =@company.city
%p
  %strong Nonprofit:
  =@company.nonprofit

=link_to "All companies", root_path
|
=link_to "Edit company", edit_company_path  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CompanyDirectory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>